#### Pandas for Data Manipulation, Analysis and preparation

### Importing libraries

In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

### Loading our Data into Pandas Data Frame

In [2]:
# Import our Data into a data frame
df = pd.read_csv(r"C:\Users\Admin\Desktop\My-Python-Class\Data\Homelessness.csv")

#### Exploring our Data

In [3]:
# viewing the 1st 6, ()gives 1st 5
df.head(6)

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588
5,5,Mountain,Colorado,7607.0,3250.0,5691287

In [4]:
# Viewing the last 5 rows
df.tail()

,Unnamed: 0,region,state,individuals,family_members,state_pop
46,46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,47,Pacific,Washington,16424.0,5880.0,7523869
48,48,South Atlantic,West Virginia,1021.0,222.0,1804291
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
50,50,Mountain,Wyoming,434.0,205.0,577601

In [5]:
# Get Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      51 non-null     int64
 1   region          51 non-null     str
 2   state           51 non-null     str
 3   individuals     51 non-null     float64
 4   family_members  51 non-null     float64
 5   state_pop       51 non-null     int64
dtypes: float64(2), int64(2), str(2)
memory usage: 2.5 KB

In [6]:
# Getting the number of rows and columns in my data frame, 51 rows and 6 columns
df.shape

(51, 6)

In [7]:
# Getting the summary statistics of the dataset\
df.describe()

       Unnamed: 0    individuals  family_members     state_pop
count   51.000000      51.000000       51.000000  5.100000e+01
mean    25.000000    7225.784314     3504.882353  6.405637e+06
std     14.866069   15991.025083     7805.411811  7.327258e+06
min      0.000000     434.000000       75.000000  5.776010e+05
25%     12.500000    1446.500000      592.000000  1.777414e+06
50%     25.000000    3082.000000     1482.000000  4.461153e+06
75%     37.500000    6781.500000     3196.000000  7.340946e+06
max     50.000000  109008.000000    52070.000000  3.946159e+07

In [8]:
df.values

array([[0, 'East South Central', 'Alabama', 2570.0, 864.0, 4887681],
       [1, 'Pacific', 'Alaska', 1434.0, 582.0, 735139],
       [2, 'Mountain', 'Arizona', 7259.0, 2606.0, 7158024],
       [3, 'West South Central', 'Arkansas', 2280.0, 432.0, 3009733],
       [4, 'Pacific', 'California', 109008.0, 20964.0, 39461588],
       [5, 'Mountain', 'Colorado', 7607.0, 3250.0, 5691287],
       [6, 'New England', 'Connecticut', 2280.0, 1696.0, 3571520],
       [7, 'South Atlantic', 'Delaware', 708.0, 374.0, 965479],
       [8, 'South Atlantic', 'District of Columbia', 3770.0, 3134.0,
        701547],
       [9, 'South Atlantic', 'Florida', 21443.0, 9587.0, 21244317],
       [10, 'South Atlantic', 'Georgia', 6943.0, 2556.0, 10511131],
       [11, 'Pacific', 'Hawaii', 4131.0, 2399.0, 1420593],
       [12, 'Mountain', 'Idaho', 1297.0, 715.0, 1750536],
       [13, 'East North Central', 'Illinois', 6752.0, 3891.0, 12723071],
       [14, 'East North Central', 'Indiana', 3776.0, 1482.0, 6695497],
       [15, 'West North Central', 'Iowa', 1711.0, 1038.0, 3148618],
       [16, 'West North Central', 'Kansas', 1443.0, 773.0, 2911359],
       [17, 'East South Central', 'Kentucky', 2735.0, 953.0, 4461153],
       [18, 'West South Central', 'Louisiana', 2540.0, 519.0, 4659690],
       [19, 'New England', 'Maine', 1450.0, 1066.0, 1339057],
       [20, 'South Atlantic', 'Maryland', 4914.0, 2230.0, 6035802],
       [21, 'New England', 'Massachusetts', 6811.0, 13257.0, 6882635],
       [22, 'East North Central', 'Michigan', 5209.0, 3142.0, 9984072],
       [23, 'West North Central', 'Minnesota', 3993.0, 3250.0, 5606249],
       [24, 'East South Central', 'Mississippi', 1024.0, 328.0, 2981020],
       [25, 'West North Central', 'Missouri', 3776.0, 2107.0, 6121623],
       [26, 'Mountain', 'Montana', 983.0, 422.0, 1060665],
       [27, 'West North Central', 'Nebraska', 1745.0, 676.0, 1925614],
       [28, 'Mountain', 'Nevada', 7058.0, 486.0, 3027341],
       [29, 'New England', 'New Hampshire', 835.0, 615.0, 1353465],
       [30, 'Mid-Atlantic', 'New Jersey', 6048.0, 3350.0, 8886025],
       [31, 'Mountain', 'New Mexico', 1949.0, 602.0, 2092741],
       [32, 'Mid-Atlantic', 'New York', 39827.0, 52070.0, 19530351],
       [33, 'South Atlantic', 'North Carolina', 6451.0, 2817.0, 10381615],
       [34, 'West North Central', 'North Dakota', 467.0, 75.0, 758080],
       [35, 'East North Central', 'Ohio', 6929.0, 3320.0, 11676341],
       [36, 'West South Central', 'Oklahoma', 2823.0, 1048.0, 3940235],
       [37, 'Pacific', 'Oregon', 11139.0, 3337.0, 4181886],
       [38, 'Mid-Atlantic', 'Pennsylvania', 8163.0, 5349.0, 12800922],
       [39, 'New England', 'Rhode Island', 747.0, 354.0, 1058287],
       [40, 'South Atlantic', 'South Carolina', 3082.0, 851.0, 5084156],
       [41, 'West North Central', 'South Dakota', 836.0, 323.0, 878698],
       [42, 'East South Central', 'Tennessee', 6139.0, 1744.0, 6771631],
       [43, 'West South Central', 'Texas', 19199.0, 6111.0, 28628666],
       [44, 'Mountain', 'Utah', 1904.0, 972.0, 3153550],
       [45, 'New England', 'Vermont', 780.0, 511.0, 624358],
       [46, 'South Atlantic', 'Virginia', 3928.0, 2047.0, 8501286],
       [47, 'Pacific', 'Washington', 16424.0, 5880.0, 7523869],
       [48, 'South Atlantic', 'West Virginia', 1021.0, 222.0, 1804291],
       [49, 'East North Central', 'Wisconsin', 2740.0, 2167.0, 5807406],
       [50, 'Mountain', 'Wyoming', 434.0, 205.0, 577601]], dtype=object)

In [9]:
df.columns

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='str')

In [10]:
df.index

RangeIndex(start=0, stop=51, step=1)


### Data Cleaning

- Deleting the Unnamed: 0 Column since its just a duplicate of the index column

#### Sorting and subsetting in pandas

In [11]:
# Drop 'the Unnamed: 0' column from the dataframe
df = df.drop(columns="Unnamed: 0")

In [12]:
df.columns

Index(['region', 'state', 'individuals', 'family_members', 'state_pop'], dtype='str')

###  Sorting values

In [13]:
df.head()

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

In [14]:
# sorting the data frame by the 'state_pop' column in ascending order
df.sort_values("state_pop")

,region,state,individuals,family_members,state_pop
50,Mountain,Wyoming,434.0,205.0,577601
45,New England,Vermont,780.0,511.0,624358
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
1,Pacific,Alaska,1434.0,582.0,735139
34,West North Central,North Dakota,467.0,75.0,758080
41,West North Central,South Dakota,836.0,323.0,878698
7,South Atlantic,Delaware,708.0,374.0,965479
39,New England,Rhode Island,747.0,354.0,1058287
26,Mountain,Montana,983.0,422.0,1060665
19,New England,Maine,1450.0,1066.0,1339057
29,New England,New Hampshire,835.0,615.0,1353465
11,Pacific,Hawaii,4131.0,2399.0,1420593
12,Mountain,Idaho,1297.0,715.0,1750536
48,South Atlantic,West Virginia,1021.0,222.0,1804291
27,West North Central,Nebraska,1745.0,676.0,1925614
31,Mountain,New Mexico,1949.0,602.0,2092741
16,West North Central,Kansas,1443.0,773.0,2911359
24,East South Central,Mississippi,1024.0,328.0,2981020
3,West South Central,Arkansas,2280.0,432.0,3009733
28,Mountain,Nevada,7058.0,486.0,3027341
15,West North Central,Iowa,1711.0,1038.0,3148618
44,Mountain,Utah,1904.0,972.0,3153550
6,New England,Connecticut,2280.0,1696.0,3571520
36,West South Central,Oklahoma,2823.0,1048.0,3940235
37,Pacific,Oregon,11139.0,3337.0,4181886
17,East South Central,Kentucky,2735.0,953.0,4461153
18,West South Central,Louisiana,2540.0,519.0,4659690
0,East South Central,Alabama,2570.0,864.0,4887681
40,South Atlantic,South Carolina,3082.0,851.0,5084156
23,West North Central,Minnesota,3993.0,3250.0,5606249
5,Mountain,Colorado,7607.0,3250.0,5691287
49,East North Central,Wisconsin,2740.0,2167.0,5807406
20,South Atlantic,Maryland,4914.0,2230.0,6035802
25,West North Central,Missouri,3776.0,2107.0,6121623
14,East North Central,Indiana,3776.0,1482.0,6695497
42,East South Central,Tennessee,6139.0,1744.0,6771631
21,New England,Massachusetts,6811.0,13257.0,6882635
2,Mountain,Arizona,7259.0,2606.0,7158024
47,Pacific,Washington,16424.0,5880.0,7523869
46,South Atlantic,Virginia,3928.0,2047.0,8501286
30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025
22,East North Central,Michigan,5209.0,3142.0,9984072
33,South Atlantic,North Carolina,6451.0,2817.0,10381615
10,South Atlantic,Georgia,6943.0,2556.0,10511131
35,East North Central,Ohio,6929.0,3320.0,11676341
13,East North Central,Illinois,6752.0,3891.0,12723071
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
32,Mid-Atlantic,New York,39827.0,52070.0,19530351
9,South Atlantic,Florida,21443.0,9587.0,21244317
43,West South Central,Texas,19199.0,6111.0,28628666
4,Pacific,California,109008.0,20964.0,39461588

In [15]:
# sorting the data frame by the 'state_pop' in descending order
df.sort_values("state_pop", ascending=False)

,region,state,individuals,family_members,state_pop
4,Pacific,California,109008.0,20964.0,39461588
43,West South Central,Texas,19199.0,6111.0,28628666
9,South Atlantic,Florida,21443.0,9587.0,21244317
32,Mid-Atlantic,New York,39827.0,52070.0,19530351
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
13,East North Central,Illinois,6752.0,3891.0,12723071
35,East North Central,Ohio,6929.0,3320.0,11676341
10,South Atlantic,Georgia,6943.0,2556.0,10511131
33,South Atlantic,North Carolina,6451.0,2817.0,10381615
22,East North Central,Michigan,5209.0,3142.0,9984072
30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025
46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,Pacific,Washington,16424.0,5880.0,7523869
2,Mountain,Arizona,7259.0,2606.0,7158024
21,New England,Massachusetts,6811.0,13257.0,6882635
42,East South Central,Tennessee,6139.0,1744.0,6771631
14,East North Central,Indiana,3776.0,1482.0,6695497
25,West North Central,Missouri,3776.0,2107.0,6121623
20,South Atlantic,Maryland,4914.0,2230.0,6035802
49,East North Central,Wisconsin,2740.0,2167.0,5807406
5,Mountain,Colorado,7607.0,3250.0,5691287
23,West North Central,Minnesota,3993.0,3250.0,5606249
40,South Atlantic,South Carolina,3082.0,851.0,5084156
0,East South Central,Alabama,2570.0,864.0,4887681
18,West South Central,Louisiana,2540.0,519.0,4659690
17,East South Central,Kentucky,2735.0,953.0,4461153
37,Pacific,Oregon,11139.0,3337.0,4181886
36,West South Central,Oklahoma,2823.0,1048.0,3940235
6,New England,Connecticut,2280.0,1696.0,3571520
44,Mountain,Utah,1904.0,972.0,3153550
15,West North Central,Iowa,1711.0,1038.0,3148618
28,Mountain,Nevada,7058.0,486.0,3027341
3,West South Central,Arkansas,2280.0,432.0,3009733
24,East South Central,Mississippi,1024.0,328.0,2981020
16,West North Central,Kansas,1443.0,773.0,2911359
31,Mountain,New Mexico,1949.0,602.0,2092741
27,West North Central,Nebraska,1745.0,676.0,1925614
48,South Atlantic,West Virginia,1021.0,222.0,1804291
12,Mountain,Idaho,1297.0,715.0,1750536
11,Pacific,Hawaii,4131.0,2399.0,1420593
29,New England,New Hampshire,835.0,615.0,1353465
19,New England,Maine,1450.0,1066.0,1339057
26,Mountain,Montana,983.0,422.0,1060665
39,New England,Rhode Island,747.0,354.0,1058287
7,South Atlantic,Delaware,708.0,374.0,965479
41,West North Central,South Dakota,836.0,323.0,878698
34,West North Central,North Dakota,467.0,75.0,758080
1,Pacific,Alaska,1434.0,582.0,735139
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
45,New England,Vermont,780.0,511.0,624358
50,Mountain,Wyoming,434.0,205.0,577601

### Sorting by multiple variables

In [16]:
df.sort_values(["state_pop", "family_members"], ascending =[False, False]),

(                region                 state  individuals  family_members  \
 4              Pacific            California     109008.0         20964.0
 43  West South Central                 Texas      19199.0          6111.0
 9       South Atlantic               Florida      21443.0          9587.0
 32        Mid-Atlantic              New York      39827.0         52070.0
 38        Mid-Atlantic          Pennsylvania       8163.0          5349.0
 13  East North Central              Illinois       6752.0          3891.0
 35  East North Central                  Ohio       6929.0          3320.0
 10      South Atlantic               Georgia       6943.0          2556.0
 33      South Atlantic        North Carolina       6451.0          2817.0
 22  East North Central              Michigan       5209.0          3142.0
 30        Mid-Atlantic            New Jersey       6048.0          3350.0
 46      South Atlantic              Virginia       3928.0          2047.0
 47             Pacific            Washington      16424.0          5880.0
 2             Mountain               Arizona       7259.0          2606.0
 21         New England         Massachusetts       6811.0         13257.0
 42  East South Central             Tennessee       6139.0          1744.0
 14  East North Central               Indiana       3776.0          1482.0
 25  West North Central              Missouri       3776.0          2107.0
 20      South Atlantic              Maryland       4914.0          2230.0
 49  East North Central             Wisconsin       2740.0          2167.0
 5             Mountain              Colorado       7607.0          3250.0
 23  West North Central             Minnesota       3993.0          3250.0
 40      South Atlantic        South Carolina       3082.0           851.0
 0   East South Central               Alabama       2570.0           864.0
 18  West South Central             Louisiana       2540.0           519.0
 17  East South Central              Kentucky       2735.0           953.0
 37             Pacific                Oregon      11139.0          3337.0
 36  West South Central              Oklahoma       2823.0          1048.0
 6          New England           Connecticut       2280.0          1696.0
 44            Mountain                  Utah       1904.0           972.0
 15  West North Central                  Iowa       1711.0          1038.0
 28            Mountain                Nevada       7058.0           486.0
 3   West South Central              Arkansas       2280.0           432.0
 24  East South Central           Mississippi       1024.0           328.0
 16  West North Central                Kansas       1443.0           773.0
 31            Mountain            New Mexico       1949.0           602.0
 27  West North Central              Nebraska       1745.0           676.0
 48      South Atlantic         West Virginia       1021.0           222.0
 12            Mountain                 Idaho       1297.0           715.0
 11             Pacific                Hawaii       4131.0          2399.0
 29         New England         New Hampshire        835.0           615.0
 19         New England                 Maine       1450.0          1066.0
 26            Mountain               Montana        983.0           422.0
 39         New England          Rhode Island        747.0           354.0
 7       South Atlantic              Delaware        708.0           374.0
 41  West North Central          South Dakota        836.0           323.0
 34  West North Central          North Dakota        467.0            75.0
 1              Pacific                Alaska       1434.0           582.0
 8       South Atlantic  District of Columbia       3770.0          3134.0
 45         New England               Vermont        780.0           511.0
 50            Mountain               Wyoming        434.0           205.0

     state_pop
 4    39461588
 43   28628666
 9    21244317
 32   19530351
 38   12800922
 13   12723071
 35   11676341
 10   10511131
 33   10381615
 22    9984072
 30    8886025
 46    8501286
 47    7523869
 2     7158024
 21    6882635
 42    6771631
 14    6695497
 25    6121623
 20    6035802
 49    5807406
 5     5691287
 23    5606249
 40    5084156
 0     4887681
 18    4659690
 17    4461153
 37    4181886
 36    3940235
 6     3571520
 44    3153550
 15    3148618
 28    3027341
 3     3009733
 24    2981020
 16    2911359
 31    2092741
 27    1925614
 48    1804291
 12    1750536
 11    1420593
 29    1353465
 19    1339057
 26    1060665
 39    1058287
 7      965479
 41     878698
 34     758080
 1      735139
 8      701547
 45     624358
 50     577601  ,)

In [17]:
df.sort_values

<bound method DataFrame.sort_values of                 region                 state  individuals  family_members  \
0   East South Central               Alabama       2570.0           864.0
1              Pacific                Alaska       1434.0           582.0
2             Mountain               Arizona       7259.0          2606.0
3   West South Central              Arkansas       2280.0           432.0
4              Pacific            California     109008.0         20964.0
5             Mountain              Colorado       7607.0          3250.0
6          New England           Connecticut       2280.0          1696.0
7       South Atlantic              Delaware        708.0           374.0
8       South Atlantic  District of Columbia       3770.0          3134.0
9       South Atlantic               Florida      21443.0          9587.0
10      South Atlantic               Georgia       6943.0          2556.0
11             Pacific                Hawaii       4131.0          2399.0
12            Mountain                 Idaho       1297.0           715.0
13  East North Central              Illinois       6752.0          3891.0
14  East North Central               Indiana       3776.0          1482.0
15  West North Central                  Iowa       1711.0          1038.0
16  West North Central                Kansas       1443.0           773.0
17  East South Central              Kentucky       2735.0           953.0
18  West South Central             Louisiana       2540.0           519.0
19         New England                 Maine       1450.0          1066.0
20      South Atlantic              Maryland       4914.0          2230.0
21         New England         Massachusetts       6811.0         13257.0
22  East North Central              Michigan       5209.0          3142.0
23  West North Central             Minnesota       3993.0          3250.0
24  East South Central           Mississippi       1024.0           328.0
25  West North Central              Missouri       3776.0          2107.0
26            Mountain               Montana        983.0           422.0
27  West North Central              Nebraska       1745.0           676.0
28            Mountain                Nevada       7058.0           486.0
29         New England         New Hampshire        835.0           615.0
30        Mid-Atlantic            New Jersey       6048.0          3350.0
31            Mountain            New Mexico       1949.0           602.0
32        Mid-Atlantic              New York      39827.0         52070.0
33      South Atlantic        North Carolina       6451.0          2817.0
34  West North Central          North Dakota        467.0            75.0
35  East North Central                  Ohio       6929.0          3320.0
36  West South Central              Oklahoma       2823.0          1048.0
37             Pacific                Oregon      11139.0          3337.0
38        Mid-Atlantic          Pennsylvania       8163.0          5349.0
39         New England          Rhode Island        747.0           354.0
40      South Atlantic        South Carolina       3082.0           851.0
41  West North Central          South Dakota        836.0           323.0
42  East South Central             Tennessee       6139.0          1744.0
43  West South Central                 Texas      19199.0          6111.0
44            Mountain                  Utah       1904.0           972.0
45         New England               Vermont        780.0           511.0
46      South Atlantic              Virginia       3928.0          2047.0
47             Pacific            Washington      16424.0          5880.0
48      South Atlantic         West Virginia       1021.0           222.0
49  East North Central             Wisconsin       2740.0          2167.0
50            Mountain               Wyoming        434.0           205.0

    state_pop
0     4887681
1      735139
2     7158024
3     3009733
4    39461588
5     5691287
6     3571520
7      965479
8      701547
9    21244317
10   10511131
11    1420593
12    1750536
13   12723071
14    6695497
15    3148618
16    2911359
17    4461153
18    4659690
19    1339057
20    6035802
21    6882635
22    9984072
23    5606249
24    2981020
25    6121623
26    1060665
27    1925614
28    3027341
29    1353465
30    8886025
31    2092741
32   19530351
33   10381615
34     758080
35   11676341
36    3940235
37    4181886
38   12800922
39    1058287
40    5084156
41     878698
42    6771631
43   28628666
44    3153550
45     624358
46    8501286
47    7523869
48    1804291
49    5807406
50     577601  >

### Combining Datasets Concat and Append

#### Simple concatenation with pd.concat

- Pandas has a function, pd.concat(), which has a similar syntax to np.concatenate but contains a number of options

### Combining Datasets using concat

In [18]:
df

,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570.0,864.0,4887681
1,Pacific,Alaska,1434.0,582.0,735139
2,Mountain,Arizona,7259.0,2606.0,7158024
3,West South Central,Arkansas,2280.0,432.0,3009733
4,Pacific,California,109008.0,20964.0,39461588
5,Mountain,Colorado,7607.0,3250.0,5691287
6,New England,Connecticut,2280.0,1696.0,3571520
7,South Atlantic,Delaware,708.0,374.0,965479
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,South Atlantic,Florida,21443.0,9587.0,21244317
10,South Atlantic,Georgia,6943.0,2556.0,10511131
11,Pacific,Hawaii,4131.0,2399.0,1420593
12,Mountain,Idaho,1297.0,715.0,1750536
13,East North Central,Illinois,6752.0,3891.0,12723071
14,East North Central,Indiana,3776.0,1482.0,6695497
15,West North Central,Iowa,1711.0,1038.0,3148618
16,West North Central,Kansas,1443.0,773.0,2911359
17,East South Central,Kentucky,2735.0,953.0,4461153
18,West South Central,Louisiana,2540.0,519.0,4659690
19,New England,Maine,1450.0,1066.0,1339057
20,South Atlantic,Maryland,4914.0,2230.0,6035802
21,New England,Massachusetts,6811.0,13257.0,6882635
22,East North Central,Michigan,5209.0,3142.0,9984072
23,West North Central,Minnesota,3993.0,3250.0,5606249
24,East South Central,Mississippi,1024.0,328.0,2981020
25,West North Central,Missouri,3776.0,2107.0,6121623
26,Mountain,Montana,983.0,422.0,1060665
27,West North Central,Nebraska,1745.0,676.0,1925614
28,Mountain,Nevada,7058.0,486.0,3027341
29,New England,New Hampshire,835.0,615.0,1353465
30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025
31,Mountain,New Mexico,1949.0,602.0,2092741
32,Mid-Atlantic,New York,39827.0,52070.0,19530351
33,South Atlantic,North Carolina,6451.0,2817.0,10381615
34,West North Central,North Dakota,467.0,75.0,758080
35,East North Central,Ohio,6929.0,3320.0,11676341
36,West South Central,Oklahoma,2823.0,1048.0,3940235
37,Pacific,Oregon,11139.0,3337.0,4181886
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
39,New England,Rhode Island,747.0,354.0,1058287
40,South Atlantic,South Carolina,3082.0,851.0,5084156
41,West North Central,South Dakota,836.0,323.0,878698
42,East South Central,Tennessee,6139.0,1744.0,6771631
43,West South Central,Texas,19199.0,6111.0,28628666
44,Mountain,Utah,1904.0,972.0,3153550
45,New England,Vermont,780.0,511.0,624358
46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,Pacific,Washington,16424.0,5880.0,7523869
48,South Atlantic,West Virginia,1021.0,222.0,1804291
49,East North Central,Wisconsin,2740.0,2167.0,5807406
50,Mountain,Wyoming,434.0,205.0,577601

In [19]:
df[: 5]

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

In [20]:
df[5:10]

,region,state,individuals,family_members,state_pop
5,Mountain,Colorado,7607.0,3250.0,5691287
6,New England,Connecticut,2280.0,1696.0,3571520
7,South Atlantic,Delaware,708.0,374.0,965479
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,South Atlantic,Florida,21443.0,9587.0,21244317

In [21]:
df1 = df[: 5]

In [22]:
df2 = df[5:10]

In [23]:
all_data = pd.concat([df1, df2])
all_data

,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570.0,864.0,4887681
1,Pacific,Alaska,1434.0,582.0,735139
2,Mountain,Arizona,7259.0,2606.0,7158024
3,West South Central,Arkansas,2280.0,432.0,3009733
4,Pacific,California,109008.0,20964.0,39461588
5,Mountain,Colorado,7607.0,3250.0,5691287
6,New England,Connecticut,2280.0,1696.0,3571520
7,South Atlantic,Delaware,708.0,374.0,965479
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,South Atlantic,Florida,21443.0,9587.0,21244317

In [24]:
df

,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570.0,864.0,4887681
1,Pacific,Alaska,1434.0,582.0,735139
2,Mountain,Arizona,7259.0,2606.0,7158024
3,West South Central,Arkansas,2280.0,432.0,3009733
4,Pacific,California,109008.0,20964.0,39461588
5,Mountain,Colorado,7607.0,3250.0,5691287
6,New England,Connecticut,2280.0,1696.0,3571520
7,South Atlantic,Delaware,708.0,374.0,965479
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,South Atlantic,Florida,21443.0,9587.0,21244317
10,South Atlantic,Georgia,6943.0,2556.0,10511131
11,Pacific,Hawaii,4131.0,2399.0,1420593
12,Mountain,Idaho,1297.0,715.0,1750536
13,East North Central,Illinois,6752.0,3891.0,12723071
14,East North Central,Indiana,3776.0,1482.0,6695497
15,West North Central,Iowa,1711.0,1038.0,3148618
16,West North Central,Kansas,1443.0,773.0,2911359
17,East South Central,Kentucky,2735.0,953.0,4461153
18,West South Central,Louisiana,2540.0,519.0,4659690
19,New England,Maine,1450.0,1066.0,1339057
20,South Atlantic,Maryland,4914.0,2230.0,6035802
21,New England,Massachusetts,6811.0,13257.0,6882635
22,East North Central,Michigan,5209.0,3142.0,9984072
23,West North Central,Minnesota,3993.0,3250.0,5606249
24,East South Central,Mississippi,1024.0,328.0,2981020
25,West North Central,Missouri,3776.0,2107.0,6121623
26,Mountain,Montana,983.0,422.0,1060665
27,West North Central,Nebraska,1745.0,676.0,1925614
28,Mountain,Nevada,7058.0,486.0,3027341
29,New England,New Hampshire,835.0,615.0,1353465
30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025
31,Mountain,New Mexico,1949.0,602.0,2092741
32,Mid-Atlantic,New York,39827.0,52070.0,19530351
33,South Atlantic,North Carolina,6451.0,2817.0,10381615
34,West North Central,North Dakota,467.0,75.0,758080
35,East North Central,Ohio,6929.0,3320.0,11676341
36,West South Central,Oklahoma,2823.0,1048.0,3940235
37,Pacific,Oregon,11139.0,3337.0,4181886
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
39,New England,Rhode Island,747.0,354.0,1058287
40,South Atlantic,South Carolina,3082.0,851.0,5084156
41,West North Central,South Dakota,836.0,323.0,878698
42,East South Central,Tennessee,6139.0,1744.0,6771631
43,West South Central,Texas,19199.0,6111.0,28628666
44,Mountain,Utah,1904.0,972.0,3153550
45,New England,Vermont,780.0,511.0,624358
46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,Pacific,Washington,16424.0,5880.0,7523869
48,South Atlantic,West Virginia,1021.0,222.0,1804291
49,East North Central,Wisconsin,2740.0,2167.0,5807406
50,Mountain,Wyoming,434.0,205.0,577601

In [25]:
df[15:19]

                region      state  individuals  family_members  state_pop
15  West North Central       Iowa       1711.0          1038.0    3148618
16  West North Central     Kansas       1443.0           773.0    2911359
17  East South Central   Kentucky       2735.0           953.0    4461153
18  West South Central  Louisiana       2540.0           519.0    4659690

In [26]:
df[25:29]

                region     state  individuals  family_members  state_pop
25  West North Central  Missouri       3776.0          2107.0    6121623
26            Mountain   Montana        983.0           422.0    1060665
27  West North Central  Nebraska       1745.0           676.0    1925614
28            Mountain    Nevada       7058.0           486.0    3027341

In [27]:
df3 = df[15:19]

In [28]:
df4 = df[25:29]

In [29]:
all_data = pd.concat([df3, df4])

In [30]:
all_data

                region      state  individuals  family_members  state_pop
15  West North Central       Iowa       1711.0          1038.0    3148618
16  West North Central     Kansas       1443.0           773.0    2911359
17  East South Central   Kentucky       2735.0           953.0    4461153
18  West South Central  Louisiana       2540.0           519.0    4659690
25  West North Central   Missouri       3776.0          2107.0    6121623
26            Mountain    Montana        983.0           422.0    1060665
27  West North Central   Nebraska       1745.0           676.0    1925614
28            Mountain     Nevada       7058.0           486.0    3027341

In [31]:
pd.concat([df3, df4], axis = 0)

                region      state  individuals  family_members  state_pop
15  West North Central       Iowa       1711.0          1038.0    3148618
16  West North Central     Kansas       1443.0           773.0    2911359
17  East South Central   Kentucky       2735.0           953.0    4461153
18  West South Central  Louisiana       2540.0           519.0    4659690
25  West North Central   Missouri       3776.0          2107.0    6121623
26            Mountain    Montana        983.0           422.0    1060665
27  West North Central   Nebraska       1745.0           676.0    1925614
28            Mountain     Nevada       7058.0           486.0    3027341

In [32]:
df3

                region      state  individuals  family_members  state_pop
15  West North Central       Iowa       1711.0          1038.0    3148618
16  West North Central     Kansas       1443.0           773.0    2911359
17  East South Central   Kentucky       2735.0           953.0    4461153
18  West South Central  Louisiana       2540.0           519.0    4659690

In [33]:
df4

                region     state  individuals  family_members  state_pop
25  West North Central  Missouri       3776.0          2107.0    6121623
26            Mountain   Montana        983.0           422.0    1060665
27  West North Central  Nebraska       1745.0           676.0    1925614
28            Mountain    Nevada       7058.0           486.0    3027341

In [34]:
pd.concat([df3, df4], join='inner')

                region      state  individuals  family_members  state_pop
15  West North Central       Iowa       1711.0          1038.0    3148618
16  West North Central     Kansas       1443.0           773.0    2911359
17  East South Central   Kentucky       2735.0           953.0    4461153
18  West South Central  Louisiana       2540.0           519.0    4659690
25  West North Central   Missouri       3776.0          2107.0    6121623
26            Mountain    Montana        983.0           422.0    1060665
27  West North Central   Nebraska       1745.0           676.0    1925614
28            Mountain     Nevada       7058.0           486.0    3027341

### Combining datasets Merge and Join

In [35]:
pd.merge(df1,df2)

Empty DataFrame
Columns: [region, state, individuals, family_members, state_pop]
Index: []

In [36]:
df6 = pd.merge(df1,df2)

In [37]:
df6

Empty DataFrame
Columns: [region, state, individuals, family_members, state_pop]
Index: []

In [38]:
display('df1', 'df2', 'df6')

'df1'

'df2'

'df6'

### Specification of the merge Key

In [39]:
display('df1', 'df4', "pd.merge(df1, df4, on='family_members')")

'df1'

'df4'

"pd.merge(df1, df4, on='family_members')"

In [40]:
display('df1', 'df4', "pd.merge(df1, df4, on='state')")

'df1'

'df4'

"pd.merge(df1, df4, on='state')"

**The left_index and right_index keywords**
- Sometimes, rather than merging on a column, you would instead like to merge on an index. For example, your data might look like this:

In [41]:
df1a = df1.set_index('family_members')
df2a = df2.set_index('state')
display('df1a', 'df2a')

'df1a'

'df2a'

In [42]:
display('df1a', 'df2a',
        "pd.merge(df1a, df2a, left_index=True, right_index=True)")

'df1a'

'df2a'

'pd.merge(df1a, df2a, left_index=True, right_index=True)'

In [43]:
pd.merge(df1a, df2a, left_index=True, right_index=True)

Empty DataFrame
Columns: [region_x, state, individuals_x, state_pop_x, region_y, individuals_y, family_members, state_pop_y]
Index: []

In [44]:
pd.merge(df1, df2, how='inner')

Empty DataFrame
Columns: [region, state, individuals, family_members, state_pop]
Index: []

In [45]:
state_info = pd.DataFrame({"state": ["California", "Texas", "New York"], "capital":["Los Angeles", "Austin", "Albany"]})

In [46]:
merged = pd.merge(df, state_info, on="state")

In [47]:
merged.head()

,region,state,individuals,family_members,state_pop,capital
0,Pacific,California,109008.0,20964.0,39461588,Los Angeles
1,Mid-Atlantic,New York,39827.0,52070.0,19530351,Albany
2,West South Central,Texas,19199.0,6111.0,28628666,Austin

In [48]:
all_data = pd.concat([df1, df2], axis=0)
all_data

,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570.0,864.0,4887681
1,Pacific,Alaska,1434.0,582.0,735139
2,Mountain,Arizona,7259.0,2606.0,7158024
3,West South Central,Arkansas,2280.0,432.0,3009733
4,Pacific,California,109008.0,20964.0,39461588
5,Mountain,Colorado,7607.0,3250.0,5691287
6,New England,Connecticut,2280.0,1696.0,3571520
7,South Atlantic,Delaware,708.0,374.0,965479
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,South Atlantic,Florida,21443.0,9587.0,21244317

In [49]:
all_data = pd.concat([df3, df4], axis=0)
all_data

                region      state  individuals  family_members  state_pop
15  West North Central       Iowa       1711.0          1038.0    3148618
16  West North Central     Kansas       1443.0           773.0    2911359
17  East South Central   Kentucky       2735.0           953.0    4461153
18  West South Central  Louisiana       2540.0           519.0    4659690
25  West North Central   Missouri       3776.0          2107.0    6121623
26            Mountain    Montana        983.0           422.0    1060665
27  West North Central   Nebraska       1745.0           676.0    1925614
28            Mountain     Nevada       7058.0           486.0    3027341

In [50]:
all_data = pd.concat([df1, df2], axis=0, ignore_index=True)
all_data

,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570.0,864.0,4887681
1,Pacific,Alaska,1434.0,582.0,735139
2,Mountain,Arizona,7259.0,2606.0,7158024
3,West South Central,Arkansas,2280.0,432.0,3009733
4,Pacific,California,109008.0,20964.0,39461588
5,Mountain,Colorado,7607.0,3250.0,5691287
6,New England,Connecticut,2280.0,1696.0,3571520
7,South Atlantic,Delaware,708.0,374.0,965479
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,South Atlantic,Florida,21443.0,9587.0,21244317

In [51]:
all_data = pd.concat([df3, df4], axis=0, ignore_index=False)
all_data

                region      state  individuals  family_members  state_pop
15  West North Central       Iowa       1711.0          1038.0    3148618
16  West North Central     Kansas       1443.0           773.0    2911359
17  East South Central   Kentucky       2735.0           953.0    4461153
18  West South Central  Louisiana       2540.0           519.0    4659690
25  West North Central   Missouri       3776.0          2107.0    6121623
26            Mountain    Montana        983.0           422.0    1060665
27  West North Central   Nebraska       1745.0           676.0    1925614
28            Mountain     Nevada       7058.0           486.0    3027341

In [52]:
merged_df = pd.merge(df1, df2, how='inner')
merged_df

Empty DataFrame
Columns: [region, state, individuals, family_members, state_pop]
Index: []

In [53]:
merged.head()

,region,state,individuals,family_members,state_pop,capital
0,Pacific,California,109008.0,20964.0,39461588,Los Angeles
1,Mid-Atlantic,New York,39827.0,52070.0,19530351,Albany
2,West South Central,Texas,19199.0,6111.0,28628666,Austin

### Adding new columns

In [54]:
df.head()

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

In [55]:
df["total_homeless"] = df["individuals"] + df["family_members"]
df.head(10)

,region,state,individuals,family_members,state_pop,total_homeless
0,East South Central,Alabama,2570.0,864.0,4887681,3434.0
1,Pacific,Alaska,1434.0,582.0,735139,2016.0
2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0
3,West South Central,Arkansas,2280.0,432.0,3009733,2712.0
4,Pacific,California,109008.0,20964.0,39461588,129972.0
5,Mountain,Colorado,7607.0,3250.0,5691287,10857.0
6,New England,Connecticut,2280.0,1696.0,3571520,3976.0
7,South Atlantic,Delaware,708.0,374.0,965479,1082.0
8,South Atlantic,District of Columbia,3770.0,3134.0,701547,6904.0
9,South Atlantic,Florida,21443.0,9587.0,21244317,31030.0

In [56]:
df["pct_homeless"] = (df["total_homeless"] / df["state_pop"]) * 100
df.head(10)

,region,state,individuals,family_members,state_pop,total_homeless,pct_homeless
0,East South Central,Alabama,2570.0,864.0,4887681,3434.0,0.070258
1,Pacific,Alaska,1434.0,582.0,735139,2016.0,0.274234
2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0,0.137817
3,West South Central,Arkansas,2280.0,432.0,3009733,2712.0,0.090108
4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363
5,Mountain,Colorado,7607.0,3250.0,5691287,10857.0,0.190765
6,New England,Connecticut,2280.0,1696.0,3571520,3976.0,0.111325
7,South Atlantic,Delaware,708.0,374.0,965479,1082.0,0.112069
8,South Atlantic,District of Columbia,3770.0,3134.0,701547,6904.0,0.984111
9,South Atlantic,Florida,21443.0,9587.0,21244317,31030.0,0.146063

#### Subsetting dataframes and multiple calculations

In [57]:
states_gt_100k = df[df["total_homeless"] > 100000]
states_gt_100k

,region,state,individuals,family_members,state_pop,total_homeless,pct_homeless
4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363

In [58]:
states_gt_10k = df[df["total_homeless"] > 10000]
states_gt_10k

,region,state,individuals,family_members,state_pop,total_homeless,pct_homeless
4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363
5,Mountain,Colorado,7607.0,3250.0,5691287,10857.0,0.190765
9,South Atlantic,Florida,21443.0,9587.0,21244317,31030.0,0.146063
13,East North Central,Illinois,6752.0,3891.0,12723071,10643.0,0.083651
21,New England,Massachusetts,6811.0,13257.0,6882635,20068.0,0.291574
32,Mid-Atlantic,New York,39827.0,52070.0,19530351,91897.0,0.470534
35,East North Central,Ohio,6929.0,3320.0,11676341,10249.0,0.087776
37,Pacific,Oregon,11139.0,3337.0,4181886,14476.0,0.346160
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922,13512.0,0.105555
43,West South Central,Texas,19199.0,6111.0,28628666,25310.0,0.088408
47,Pacific,Washington,16424.0,5880.0,7523869,22304.0,0.296443

In [59]:
states_gh_30k = df[df["total_homeless"] > 30000]
states_gh_30k

,region,state,individuals,family_members,state_pop,total_homeless,pct_homeless
4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363
9,South Atlantic,Florida,21443.0,9587.0,21244317,31030.0,0.146063
32,Mid-Atlantic,New York,39827.0,52070.0,19530351,91897.0,0.470534

In [60]:
states_gh_30k = df[df["total_homeless"] > 30000]
states_gh_30k

,region,state,individuals,family_members,state_pop,total_homeless,pct_homeless
4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363
9,South Atlantic,Florida,21443.0,9587.0,21244317,31030.0,0.146063
32,Mid-Atlantic,New York,39827.0,52070.0,19530351,91897.0,0.470534

In [61]:
state_and_total_only = df.head(5)[["state", "total_homeless"]]
state_and_total_only

        state  total_homeless
0     Alabama          3434.0
1      Alaska          2016.0
2     Arizona          9865.0
3    Arkansas          2712.0
4  California        129972.0

In [62]:
# state_and_total_only = df[["state", "total_homeless", "pct_homeless"]]
state_and_total_only = df.head(5)[["state", "total_homeless", "pct_homeless"]]
state_and_total_only

        state  total_homeless  pct_homeless
0     Alabama          3434.0      0.070258
1      Alaska          2016.0      0.274234
2     Arizona          9865.0      0.137817
3    Arkansas          2712.0      0.090108
4  California        129972.0      0.329363

In [63]:
gt10k_homeless = state_and_total_only[state_and_total_only["total_homeless"] > 10000]
gt10k_homeless

        state  total_homeless  pct_homeless
4  California        129972.0      0.329363

In [64]:
gt10k_homeless.reset_index()
gt10k_homeless

        state  total_homeless  pct_homeless
4  California        129972.0      0.329363

In [65]:
no_index_gt10k = gt10k_homeless.reset_index(drop=True)
no_index_gt10k

        state  total_homeless  pct_homeless
0  California        129972.0      0.329363

In [66]:
df.head(5)

,region,state,individuals,family_members,state_pop,total_homeless,pct_homeless
0,East South Central,Alabama,2570.0,864.0,4887681,3434.0,0.070258
1,Pacific,Alaska,1434.0,582.0,735139,2016.0,0.274234
2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0,0.137817
3,West South Central,Arkansas,2280.0,432.0,3009733,2712.0,0.090108
4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363